services:
  # P2A business System Application
  p2a-business-system:
    image: ghcr.io/williamsmiths/p2a-business:v1.0.2
    container_name: p2a-business-system
    restart: always
    env_file:
      - .env
    ports:
      - "3004:3004"
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/logs:/app/logs
    networks:
      - p2a-asean-network

volumes:
  uploads_data:
    driver: local

networks:
  p2a-asean-network:
    name: p2a-asean-network
    external: true


