services:
  # P2A research System Application
  p2a-research-system:
    image: ghcr.io/williamsmiths/p2a-research:v1.0.2
    container_name: p2a-research-system
    restart: always
    env_file:
      - .env
    ports:
      - "3003:3003"
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/logs:/app/logs
    networks:
      - p2a-asean-network

volumes:
  uploads_data:
    driver: local

networks:
  p2a-asean-network:
    name: p2a-asean-network
    external: true


