services:
  # P2A Core System Application
  p2a-core-system:
    image: ghcr.io/williamsmiths/p2a-career:v1.0.1
    container_name: p2a-core-system
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/logs:/app/logs
    networks:
      - p2a-asean-network

volumes:
  uploads_data:
    driver: local

networks:
  p2a-asean-network:
    name: p2a-asean-network
    external: true


