services:
  # P2A Detect System Application
  p2a-detech-cv-system:
    image: ghcr.io/williamsmiths/detech-cv:v1.0.1
    container_name: p2a-detech-cv-system
    restart: always
    env_file:
      - .env
    ports:
      - "3005:3005"
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/logs:/app/logs
    networks:
      - p2a-asean-network

volumes:
  uploads_data:
    driver: local

networks:
  p2a-asean-network:
    name: p2a-asean-network
    external: true
    


